---
version: "3"

services:
  prometheus:
    image: prom/prometheus:latest
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  timescaledb:
    image: timescaledev/promscale-extension:latest-pg12
    restart: always
    command: postgres -csynchronous_commit=off
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: victor1234

  promscale:
    image: timescale/promscale:latest
    restart: always
    command: ' -db-password=victor1234 -db-port=5432 -db-name=postgres -db-host=timescaledb
      -db-ssl-mode=allow'
    ports:
      - "9201:9201"
